### ISSUE TITLE
integrating the “fusion\widgets”

### ISSUE THREAD

**Issue by nimcnaan** [jumpinjackie/mapguide-mvc6-sample#5]
Is there a way to integrate the “fusion\widgets”, to this example ?
with an ApplicationDefinition Layout ?

**Comment by jumpinjackie** [comment]
This is not a new map viewer. It is just the existing MapGuide Developer Guide samples ported over to asp.net core.

How this sample is to be integrated will be more fully defined once I have finished the new binding work in MapGuide OS 4.0, but I envisage how this sample to be used will be to set `http://THIS_SERVER/Samples/Home` as the initial URL of your TaskPane widget, which should then show the devguide samples landing page, which then links to all the existing examples from here. Any MVC controller route in this sample that accepts a `SESSION` and `MAPNAME` parameter are also valid candidates for InvokeURL commands in the AJAX viewer or InvokeURL widgets in Fusion.

**Comment by nimcnaan** [comment]
Thanks. We have got the samples working.
